fix release scripts

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -2,8 +2,20 @@
 
 set -e
 
+SIGNING_KEY="$HOME/.nextcloud/certificates/keeweb.key"
+
 if [ "$#" -ne 2 ]; then
   echo "Usage: bin/release version keeweb-version"
+  exit 1
+fi
+
+if [ -z "$NC_AUTH_TOKEN" ]; then
+  echo "NC_AUTH_TOKEN is unset, required to push to the appstore"
+  exit 1
+fi
+
+if [ ! -f "$SIGNING_KEY" ]; then
+  echo "$SIGNING_KEY does not exist, required to push to the appstore"
   exit 1
 fi
 
@@ -47,11 +59,7 @@ v$version
 $changelog
 EOF
 
-hub release create -F /tmp/release_notes -a "$tarball" "v$version"
+hub release create -f /tmp/release_notes -a "$tarball" "v$version"
 rm /tmp/release_notes
 
-checksum=$(sha256sum $tarball | cut -d ' ' -f1)
-download="$(hub release show --show-downloads v$version | grep "releases/download")"
-signature=$(openssl dgst -sha512 -sign ~/.nextcloud/certificates/keeweb.key "$tarball" | openssl base64)
-
-curl -X POST -H "Authorization: Token $NC_AUTH_TOKEN" https://apps.nextcloud.com/api/v1/apps/releases -H "Content-Type: application/json" -d '{"download":"$download", "signature": "$signature"}'
+bin/publish v$version "$tarball"
